### ISSUE TITLE
Error while applying role in workflow

### ISSUE THREAD

**Issue by GirishVC86** [mapcentia/geocloud2#82]
`
Uncaught TypeError: Argument 1 passed to app\models\Layer::getValueFromKey() must be of the type string, null given, called in /var/www/geocloud2/app/models/Layer.php on line 774 and defined in /var/www/geocloud2/app/models/Layer.php:50 Stack trace: #0 /var/www/geocloud2/app/models/Layer.php(774): app\models\Layer->getValueFromKey(NULL, 'roles') #1 /var/www/geocloud2/app/controllers/Layer.php(137): app\models\Layer->updateRoles(Array) #2 /var/www/geocloud2/app/inc/Route.php(77): app\controllers\Layer->put_roles(Array) #3 /var/www/geocloud2/public/index.php(304): app\inc\Route::add('controllers/Lay...') #4 {main} thrown
`

![image](https://user-images.githubusercontent.com/11706595/90497447-b9e51a00-e164-11ea-8bd7-62d0cf1a16a3.png)

**Comment by mapcentia** [comment]
Fixed
